#############################################################################
# Makefile for building: QtCamTest
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  FaaceLocker.pro
# Template: app
# Command: /opt/qt53/bin/qmake -o Makefile FaaceLocker.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -pg -g -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/qt53/mkspecs/linux-g++ -I. -isystem /usr/local/include/opencv -isystem /usr/local/include/opencv2 -I/opt/qt53/include -I/opt/qt53/include/QtWidgets -I/opt/qt53/include/QtGui -I/opt/qt53/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -fopenmp -pg -g -Wl,-O1 -Wl,-rpath,/opt/qt53/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_calib3d -lopencv_video -lopencv_features2d -lopencv_ml -lopencv_highgui -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_nonfree -lopencv_flann -L/opt/qt53/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qt53/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		engine.cpp \
		mattoimage.cpp \
		showlabel.cpp \
		object.cpp \
		utilities.cpp 
OBJECTS       = main.o \
		mainwindow.o \
		engine.o \
		mattoimage.o \
		showlabel.o \
		object.o \
		utilities.o
DIST          = /opt/qt53/mkspecs/features/spec_pre.prf \
		/opt/qt53/mkspecs/common/shell-unix.conf \
		/opt/qt53/mkspecs/common/unix.conf \
		/opt/qt53/mkspecs/common/linux.conf \
		/opt/qt53/mkspecs/common/gcc-base.conf \
		/opt/qt53/mkspecs/common/gcc-base-unix.conf \
		/opt/qt53/mkspecs/common/g++-base.conf \
		/opt/qt53/mkspecs/common/g++-unix.conf \
		/opt/qt53/mkspecs/qconfig.pri \
		/opt/qt53/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt53/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_core.pri \
		/opt/qt53/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt53/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt53/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_network.pri \
		/opt/qt53/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt53/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt53/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt53/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt53/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt53/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt53/mkspecs/features/qt_functions.prf \
		/opt/qt53/mkspecs/features/qt_config.prf \
		/opt/qt53/mkspecs/linux-g++/qmake.conf \
		/opt/qt53/mkspecs/features/spec_post.prf \
		/opt/qt53/mkspecs/features/exclusive_builds.prf \
		/opt/qt53/mkspecs/features/default_pre.prf \
		/opt/qt53/mkspecs/features/resolve_config.prf \
		/opt/qt53/mkspecs/features/default_post.prf \
		/opt/qt53/mkspecs/features/qt.prf \
		/opt/qt53/mkspecs/features/resources.prf \
		/opt/qt53/mkspecs/features/moc.prf \
		/opt/qt53/mkspecs/features/unix/opengl.prf \
		/opt/qt53/mkspecs/features/uic.prf \
		/opt/qt53/mkspecs/features/unix/thread.prf \
		/opt/qt53/mkspecs/features/warn_on.prf \
		/opt/qt53/mkspecs/features/testcase_targets.prf \
		/opt/qt53/mkspecs/features/exceptions.prf \
		/opt/qt53/mkspecs/features/yacc.prf \
		/opt/qt53/mkspecs/features/lex.prf \
		FaaceLocker.pro main.cpp \
		mainwindow.cpp \
		engine.cpp \
		mattoimage.cpp \
		showlabel.cpp \
		object.cpp \
		utilities.cpp
QMAKE_TARGET  = QtCamTest
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QtCamTest


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FaaceLocker.pro /opt/qt53/mkspecs/linux-g++/qmake.conf /opt/qt53/mkspecs/features/spec_pre.prf \
		/opt/qt53/mkspecs/common/shell-unix.conf \
		/opt/qt53/mkspecs/common/unix.conf \
		/opt/qt53/mkspecs/common/linux.conf \
		/opt/qt53/mkspecs/common/gcc-base.conf \
		/opt/qt53/mkspecs/common/gcc-base-unix.conf \
		/opt/qt53/mkspecs/common/g++-base.conf \
		/opt/qt53/mkspecs/common/g++-unix.conf \
		/opt/qt53/mkspecs/qconfig.pri \
		/opt/qt53/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt53/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_core.pri \
		/opt/qt53/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt53/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt53/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_network.pri \
		/opt/qt53/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt53/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt53/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt53/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt53/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt53/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt53/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt53/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt53/mkspecs/features/qt_functions.prf \
		/opt/qt53/mkspecs/features/qt_config.prf \
		/opt/qt53/mkspecs/linux-g++/qmake.conf \
		/opt/qt53/mkspecs/features/spec_post.prf \
		/opt/qt53/mkspecs/features/exclusive_builds.prf \
		/opt/qt53/mkspecs/features/default_pre.prf \
		/opt/qt53/mkspecs/features/resolve_config.prf \
		/opt/qt53/mkspecs/features/default_post.prf \
		/opt/qt53/mkspecs/features/qt.prf \
		/opt/qt53/mkspecs/features/resources.prf \
		/opt/qt53/mkspecs/features/moc.prf \
		/opt/qt53/mkspecs/features/unix/opengl.prf \
		/opt/qt53/mkspecs/features/uic.prf \
		/opt/qt53/mkspecs/features/unix/thread.prf \
		/opt/qt53/mkspecs/features/warn_on.prf \
		/opt/qt53/mkspecs/features/testcase_targets.prf \
		/opt/qt53/mkspecs/features/exceptions.prf \
		/opt/qt53/mkspecs/features/yacc.prf \
		/opt/qt53/mkspecs/features/lex.prf \
		FaaceLocker.pro \
		/opt/qt53/lib/libQt5Widgets.prl \
		/opt/qt53/lib/libQt5Gui.prl \
		/opt/qt53/lib/libQt5Core.prl
	$(QMAKE) -o Makefile FaaceLocker.pro
/opt/qt53/mkspecs/features/spec_pre.prf:
/opt/qt53/mkspecs/common/shell-unix.conf:
/opt/qt53/mkspecs/common/unix.conf:
/opt/qt53/mkspecs/common/linux.conf:
/opt/qt53/mkspecs/common/gcc-base.conf:
/opt/qt53/mkspecs/common/gcc-base-unix.conf:
/opt/qt53/mkspecs/common/g++-base.conf:
/opt/qt53/mkspecs/common/g++-unix.conf:
/opt/qt53/mkspecs/qconfig.pri:
/opt/qt53/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt53/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_core.pri:
/opt/qt53/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt53/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_gui.pri:
/opt/qt53/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_network.pri:
/opt/qt53/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt53/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt53/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt53/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_qml.pri:
/opt/qt53/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt53/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_quick.pri:
/opt/qt53/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt53/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_sql.pri:
/opt/qt53/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt53/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt53/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt53/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_xml.pri:
/opt/qt53/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt53/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt53/mkspecs/features/qt_functions.prf:
/opt/qt53/mkspecs/features/qt_config.prf:
/opt/qt53/mkspecs/linux-g++/qmake.conf:
/opt/qt53/mkspecs/features/spec_post.prf:
/opt/qt53/mkspecs/features/exclusive_builds.prf:
/opt/qt53/mkspecs/features/default_pre.prf:
/opt/qt53/mkspecs/features/resolve_config.prf:
/opt/qt53/mkspecs/features/default_post.prf:
/opt/qt53/mkspecs/features/qt.prf:
/opt/qt53/mkspecs/features/resources.prf:
/opt/qt53/mkspecs/features/moc.prf:
/opt/qt53/mkspecs/features/unix/opengl.prf:
/opt/qt53/mkspecs/features/uic.prf:
/opt/qt53/mkspecs/features/unix/thread.prf:
/opt/qt53/mkspecs/features/warn_on.prf:
/opt/qt53/mkspecs/features/testcase_targets.prf:
/opt/qt53/mkspecs/features/exceptions.prf:
/opt/qt53/mkspecs/features/yacc.prf:
/opt/qt53/mkspecs/features/lex.prf:
FaaceLocker.pro:
/opt/qt53/lib/libQt5Widgets.prl:
/opt/qt53/lib/libQt5Gui.prl:
/opt/qt53/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FaaceLocker.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QtCamTest1.0.0 || mkdir -p .tmp/QtCamTest1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/QtCamTest1.0.0/ && $(COPY_FILE) --parents mainwindow.h engine.h utilities.h showlabel.h object.h .tmp/QtCamTest1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp engine.cpp mattoimage.cpp showlabel.cpp object.cpp utilities.cpp .tmp/QtCamTest1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/QtCamTest1.0.0/ && (cd `dirname .tmp/QtCamTest1.0.0` && $(TAR) QtCamTest1.0.0.tar QtCamTest1.0.0 && $(COMPRESS) QtCamTest1.0.0.tar) && $(MOVE) `dirname .tmp/QtCamTest1.0.0`/QtCamTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtCamTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/qt53/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_uic_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

engine.o: engine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o engine.o engine.cpp

mattoimage.o: mattoimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mattoimage.o mattoimage.cpp

showlabel.o: showlabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showlabel.o showlabel.cpp

object.o: object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

utilities.o: utilities.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utilities.o utilities.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

