@startuml
left to right direction
interface FileSystem
interface DE
interface WebCam

package "Recognition" {
  [VideStreamProcessor] 
  [FaceFinder] 
  [UserFaceModel]
  [FaceRecognizer]
  [RecognitionFlowManager]
}
 
package "ScreenLocker" {
  [LockTimer]
  [UserPersistenceObserver]
}

package "UserInterface" {
  [InitializerView]
}

DE <-- LockTimer : Lock
LockTimer <- UserPersistenceObserver : Reset Timer

UserPersistenceObserver <-- RecognitionFlowManager : Notify if user available

RecognitionFlowManager <-- VideStreamProcessor : Video frames
RecognitionFlowManager --> FaceFinder : Get Faces on frame
RecognitionFlowManager --> FaceRecognizer : Recognize user

FaceRecognizer <--> UserFaceModel : Get model\nUpdate model
FileSystem <--> UserFaceModel 

WebCam --> VideStreamProcessor : video stream

VideStreamProcessor --> InitializerView   : Video frames
FaceFinder --> InitializerView  : Get Faces on frame
UserFaceModel <-- InitializerView  : UpdateModel
@enduml


